# Generated by Django 4.2.1 on 2024-05-27 13:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SBOM",
            fields=[
                ("serial_number", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("purl", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=63)),
                ("version", models.CharField(max_length=127)),
                ("document", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("metadata", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("ecosystem", models.CharField(max_length=64)),
                ("document", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
